# Site settings
title: NIEM
# Start with excludes that are as general as is reasonable, and we can make them
# more specific when things don't get exported
# keep this listed sorted alphabetically
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/Font-Awesome/src
  - vendor/bootstrap/docs
  - "*/aspell-exceptions.txt"
  - "*/Makefile"
  - "*.dot"
  - normative-rules-guidance/country-codes/schema.png
  - json/guidance/aux
  - json/guidance/tmp
  - site-tools
  - vendor/cache/ruby/2.4.0/gems/

gems:
  - jekyll-mentions
  - jekyll-redirect-from

repository: NIEM/niem.github.io

# Site data
superhero_iepd_path: https://github.com/NIEM/Developer-Network-IEPD-Series--SuperHero
submit_feedback_link: https://github.com/NIEM/NIEM.github.io/issues
niem_comments_link: mailto:niem-comments@lists.gatech.edu

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true
  #     start_line: 1



# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
