# Site settings
title: NIEM
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/Font-Awesome/src
  - vendor/bootstrap/docs

gems:
  - jekyll-mentions

# Site data
superhero_iepd_path: https://github.com/NIEM/Developer-Network-IEPD-Series--SuperHero
submit_feedback_link: https://github.com/NIEM/NIEM.github.io/issues
niem_comments_link: mailto:niem-comments@lists.gatech.edu

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
